package main

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/iancoleman/strcase"
)

// var _defaultProtoPkgName = "pb"

func (g *Generator) buildGraphQL(types []string, dir string) {
	var parts []string
	header := `// Code generated by \"enumer %s\"; DO NOT EDIT.

%s
`
	parts = append(parts, header)
	// Run generate for each type.
	for _, typeName := range types {
		values := g.values(typeName, "", "camel", false)
		stanza := g.createGraphQLEnumStanza(values, typeName)
		parts = append(parts, stanza)
	}

	// Format the output.
	graphqlPath := *graphqlOutput
	if graphqlPath == "" {
		baseName := defaultBaseName
		if len(types) == 1 {
			baseName = types[0]
		}
		name := strcase.ToSnake(fmt.Sprintf("%s_gen.graphql", baseName))
		graphqlPath = filepath.Join(dir, *graphqlDir, name)
	}
	text := strings.Join(parts, "\n")
	write(graphqlPath, []byte(text))
}

func (g *Generator) createGraphQLEnumStanza(values []Value, typeName string) string {
	tmpl := `enum %s {
%s
}
`
	var el []string
	for _, value := range values {
		n := value.name
		el = append(el, fmt.Sprintf("    %s", n))
	}
	return fmt.Sprintf(tmpl, typeName, strings.Join(el, "\n"))
}
